import styled from '@emotion/styled';
import Head from 'next/head';

export const Home = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
    </Container>
  );
};

const Container = styled.div``;

export default Home;
